service: salesforce-bulk 

provider:
  name: aws
  runtime: python2.7

package:
  include:
    - venv/lib/python2.7/site-packages
  exclude:
    - venv

functions:
  get:
    timeout: 300 #give the full 5min
    handler: handler.get
  update:
    timeout: 300
    handler: handler.update
  create:
    timeout: 300
    handler: handler.create
  upsert:
    timeout: 300
    handler: handler.upsert
