AWSLambdaVPCAccessExecutionRole:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    Description: Policy for allowing vpc connection.
    Roles:
      - {"Ref" : "IamRoleLambdaExecution"}
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        Effect: Allow
        Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
        Resource: "*"