service: api # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:GetFunction
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:* #let this guy call all the lambda

# Packaging
package:
  individually: true
  exclude: # Globally exclude all the submodules, each function will include their own
    - account
    - contact
    - encryption
    - event

# Functions
functions:
  account:
    handler: account/handler.account
    events:
      - http:
          method: post
          path: account
    package:
      include:
        - account
  contact:
    handler: contact/handler.contact
    events:
      - http:
          method: post
          path: contact
    package:
      include:
        - contact
  encrypt:
    handler: encryption/handler.encrypt
    events:
      - http:
          path: encryption/encrypt
          method: post
          cors: 
            origins: 
              - '*'
            headers:
              - content-type
              - x-api-key
    package:
      include:
        - encryption
  decrypt:
    handler: encryption/handler.decrypt
    events:
      - http:
          path: encryption/decrypt
          method: post
          cors: 
            origins: 
              - '*'
            headers:
              - content-type
              - x-api-key
    package:
      include:
        - encryption